steps:
  # Build the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/bazzarly-backend:$COMMIT_SHA'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'backend'

  # Push the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/bazzarly-backend:$COMMIT_SHA'

  # Deploy backend to Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'bazzarly-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/bazzarly-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=production'

# Backend Docker image
images:
  - 'gcr.io/$PROJECT_ID/bazzarly-backend:$COMMIT_SHA' 